#!/bin/bash

PACKAGES="gulp-cli gulper gulp mocha sequelize-cli"

if [[ $APP_DEBUG == 'true' ]]; then
    npm i
    
    cd scripts
    npm i
    cd ..
else
    npm i --prod

    cd scripts
    npm i --prod
    cd ..
fi

echo -e "Installing \033[32m$PACKAGES\033[0m"
if [[ APP_DEBUG == 'true' ]]; then
    npm i -g $PACKAGES
else
    npm i -g --prod $PACKAGES
fi
echo "All done."