#!/bin/bash

PACKAGES="sequelize-cli"
DEV_PGKS="gulp-cli gulper gulp mocha"

if [[ $APP_DEBUG == 'true' ]]; then
    yarn install
    
    cd scripts
    yarn install
    cd ..
else
    yarn install --prod

    cd scripts
    yarn install --prod
    cd ..

fi

echo -e "Installing \033[32m$PACKAGES\033[0m"
if [[ APP_DEBUG == 'true' ]]; then
    echo -e "Installing \033[32m$DEV_PGKS\033[0m"
    npm i -g $PACKAGES
    npm i -g $DEV_PGKS
else
    npm i -g --prod $PACKAGES
fi

echo -e "Installing resume.js"
cd react
./install_resume.sh
cd ..

echo "All done."
